name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Run tests
      run: cargo test --verbose
    - name: Run integration test (smtp)
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker build -t authoscope-smtpd ci/smtp/
        docker run --name authoscope-smtpd -d --rm -p 127.0.0.1:25:25 authoscope-smtpd

        echo root@example.com:foo > /tmp/authoscope-smtp-input.txt
        target/debug/authoscope -o authoscope-smtp-output.txt creds /tmp/authoscope-smtp-input.txt scripts/smtp.lua
        docker stop authoscope-smtpd
    - name: Verify integration test (smtp)
      if: matrix.os == 'ubuntu-latest'
      run: grep -q root@example.com authoscope-smtp-output.txt
