name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # windows currently doesn't work due to rlimit
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build (badtouch)
      run: cargo build --verbose
    - name: Build (examples)
      run: cargo build --verbose --examples
    - name: Run tests
      run: cargo test --verbose
    - name: Run integration test (smtp)
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker build -t badtouch-smtpd ci/smtp/
        docker run --name badtouch-smtpd -d --rm -p 127.0.0.1:25:25 badtouch-smtpd

        echo root@example.com:foo > /tmp/badtouch-smtp-input.txt
        target/debug/badtouch -o badtouch-smtp-output.txt creds /tmp/badtouch-smtp-input.txt scripts/smtp.lua
        docker stop badtouch-smtpd
    - name: Verify integration test (smtp)
      if: matrix.os == 'ubuntu-latest'
      run: grep -q root@example.com badtouch-smtp-output.txt
